[package]
name = "backup-gather"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bytesize = "2.0.1"
clap = { version = "4.5.45", features = ["derive"] }
log = "0.4.27"
num-format = { version = "0.4.4", features = ["with-system-locale"] }
stderrlog = "0.6.0"
